spring.datasource.url=jdbc:postgresql://dpg-d70g0i7gi27c73fhhk90-a.oregon-postgres.render.com:5432/course_db_647n
spring.datasource.username=pranay
spring.datasource.password=NaJFjroOSXkorSqA8YnqfWbgjrusgSSR
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true